package com.itmo.diplom;

import com.itmo.diplom.entity.*;
import com.itmo.diplom.repo.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import java.util.ArrayList;
import java.util.List;

@Controller
public class SystemController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CameraTypeRepository cameraTypeRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CompartmentRepository compartmentRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ControlSystemRepository controlSystemRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DecksRepository decksRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SensorsTypeRepository sensorsTypeRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private VideoEntityRepository videoEntityRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SensorsRepository sensorsRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CameraRepository cameraRepository;

    @GetMapping ("/cameras_type")
    public ModelAndView  CamerasTypeView() {
        List<CamerasType> listCamera = (ArrayList<CamerasType>) cameraTypeRepository.findAll();
        ModelAndView mav = new ModelAndView("cameras_type");
        mav.addObject("listCamera", listCamera);
        return mav;
    }

    @GetMapping ("/compartment")
    public ModelAndView  CompartmentView() {
        List<Compartment> listCompartment = (ArrayList<Compartment>) compartmentRepository.findAll();
        ModelAndView mav = new ModelAndView("compartment");
        mav.addObject("listCompartment", listCompartment);
        return mav;
    }

    @GetMapping ("/control_system")
    public ModelAndView  ControlSystemView() {
        List<ControlSystem> listControlSystem = (ArrayList<ControlSystem>) controlSystemRepository.findAll();
        ModelAndView mav = new ModelAndView("control_system");
        mav.addObject("listControlSystem", listControlSystem);
        return mav;
    }

    @GetMapping ("/decks")
    public ModelAndView  decksView() {
        List<Decks> listControlSystem = (ArrayList<Decks>) decksRepository.findAll();
        ModelAndView mav = new ModelAndView("decks");
        mav.addObject("listDecks", listControlSystem);
        return mav;
    }

    @GetMapping ("/sensors_type")
    public ModelAndView  sensorsTypeView() {
        List<SensorsType> listSystemType = (ArrayList<SensorsType>) sensorsTypeRepository.findAll();
        ModelAndView mav = new ModelAndView("sensors_type");
        mav.addObject("listSensorsType", listSystemType);
        return mav;
    }

    @GetMapping ("/video_entity")
    public ModelAndView  videoEntityView() {
        List<VideoEntity> listVideoEntity = (ArrayList<VideoEntity>) videoEntityRepository.findAll();
        ModelAndView mav = new ModelAndView("video_entity");
        mav.addObject("listVideoEntity", listVideoEntity);
        return mav;
    }

    @GetMapping ("/sensors")
    public ModelAndView  sensorsView() {
        List<Sensors> listSensors = (ArrayList<Sensors>) sensorsRepository.findAll();
        ModelAndView mav = new ModelAndView("sensors");
        mav.addObject("listSensors", listSensors);
        return mav;
    }

    @GetMapping ("/cameras")
    public ModelAndView  CamerasView() {
        List<Camera> listCameras = (ArrayList<Camera>) cameraRepository.findAll();
        ModelAndView mav = new ModelAndView("cameras");
        mav.addObject("listCameras", listCameras);
        return mav;
    }

    @GetMapping ("/info")
    public String  testView() {
        return "info";
    }

    @GetMapping ("deck")
    public String  testView2(@RequestParam(defaultValue = "1") int id, Model model){
        //TODO Использовать DeckInfoService
        List<Decks> listDecks = (ArrayList<Decks>) decksRepository.findAll();

        List<String> listLink = new ArrayList<>();

        for (Decks deck:
                listDecks) {
            String s = String.valueOf(deck.getId());
            listLink.add("/deck?id=" + s);
            model.addAttribute("link" + s, listLink.get(listLink.size() - 1));
        }

        switch (id){
            case (1): {
                String link_image = "/resources/image/2b40fd31887e6c4140ef935abe29e162.png";
                model.addAttribute("link_prev", listLink.get(0));
                model.addAttribute("link_next", listLink.get(1));
                model.addAttribute("link_image", link_image);
                model.addAttribute("name","Палуба А");
            }
            break;
            case (2): {
                String link_image = "/resources/image/2d097ac5c02d2a3670a7546537e23c66.png";
                model.addAttribute("link_prev", listLink.get(0));
                model.addAttribute("link_next", listLink.get(2));
                model.addAttribute("link_image", link_image);
                model.addAttribute("name","Палуба B");
            }
            break;
            case (3): {
                String link_image = "/resources/image/02aa0871ddba285eab67a995f319332c.png";
                model.addAttribute("link_prev", listLink.get(1));
                model.addAttribute("link_next", listLink.get(2));
                model.addAttribute("link_image", link_image);
                model.addAttribute("name","Палуба C");
            }
            break;
        }
        return "deck";
    }

    @GetMapping ("/videoarchive")
    public String  videoarchiveView() {
        //TODO Использовать DeckInfoService
        return "videoarchive";
    }
}